name: Test

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
          - os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - run: swift --version   
      - run: brew install imagemagick curl

      - name: build
        run: swift build

      - name: run sample
        run: Sample/run-sample.sh
