name: Test

on:
  push:
    branches: '**'
    pull_request:

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
          - os: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - run: swift --version   
      - run: brew install imagemagick curl

      - name: build
        run: swift build

      - name: test
        run: swift test

      - name: run sample
        run: Sample/run-sample.sh

      - name: Archive sample artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: Sample/output